# This file contains the fastlane.tools configuration

# You can find the documentation at https://docs.fastlane.tools

#

# For a list of all available actions, check out

#

#     https://docs.fastlane.tools/actions

#

# For a list of all available plugins, check out

#

#     https://docs.fastlane.tools/plugins/available-plugins

#



# Uncomment the line if you want fastlane to automatically update itself

# update_fastlane



default_platform(:android)



platform :android do

    before_all do
    ENV["FIREBASE_LOGIN_CREDENTIALS"] = "fastlane/authententicationapp-5959f9dae913.json"
    ENV["FIREBASE_APP_ID"] = "1:91922724469:android:feb45bb205a9f0f6892a3c"
    end

    gradle(task: "clean")

#     copy_artifacts(
#         artifacts: [lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]],
#         target_path: './app/Apk file/'
#       )

     # find apk path
#      output_path = "./app/Apk file/"
#      output_json_path = output_path + "output-metadata.json"
#      build_output = load_json(json_path: output_json_path)
#      elements = build_output["elements"][0]
#      apk_path = output_path + elements["outputFile"]

    desc "My awesome app"
    lane :release do
        gradle(task: "assemble",
                          flavor: "release",
                          build_type: "release",
                          properties: {
                                  "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
                                  "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
                                  "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
                                  "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
                          }
              )
        # build_android_app is a built-in fastlane action.
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            testers: "ik33218@gmail.com",
            service_credentials_file: ENV["FIREBASE_LOGIN_CREDENTIALS"],
            release_notes: "this is release build"
        )

    lane :staging do
          gradle(task: "assemble",
                 flavor: "staging",
                 build_type: "debug")
          # build_android_app is a built-in fastlane action.
          firebase_app_distribution(
             app: ENV["FIREBASE_APP_ID"],
             testers: "ik33218@gmail.com",
             service_credentials_file: ENV["FIREBASE_LOGIN_CREDENTIALS"],
             release_notes: "this is debug build"
          )
    end

end

