name: My Practice CICD

on:
  push:
    branches: [ "master" ]


jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Fastlane
      - run: bundle install

      - name: Distribute app with 🔥 App Distribution 🚀
      - run: bundle exec fastlane distribution

  
